### ISSUE TITLE
Feature request: visualize extrusion

### ISSUE THREAD

**Issue by 3d-gussner** [vintagepc/MK404#114]
Do you think it could be possible to visualize an extrusion?
Here an idea with magnifying x10
![image](https://user-images.githubusercontent.com/25530011/82731965-8122d980-9d0a-11ea-9909-bdf751742445.png)
Constant extruder move while hotend begins slow and get faster and slow again.

**Comment by 3d-gussner** [comment]
It would be great if we could also simulate the extrusion width like gcode.ws or PrusaSlicer 2.3-devel does.
![image](https://user-images.githubusercontent.com/25530011/93439808-46533b80-f8cf-11ea-91cd-a32a3f5b4fd1.png)
![image](https://user-images.githubusercontent.com/25530011/93440475-be216600-f8cf-11ea-9607-465fc41a88de.png)


@DRracer quote:
yes please do and make it work after 0.1mm segments - I'm sure we are causing the ghosting effect in the FW in the acceleration segments.
Be sure to add a multiplier to visualize the thickness e.g. 10x thicker so that we can see on single lines if the FW is computing the acceleration and deceleration correctly

**Comment by 3d-gussner** [comment]
Here a link https://github.com/hudbrog/gCodeViewer

**Comment by vintagepc** [comment]
Yes, that's the entire reason this issue is still open. I definitely want to do it and the time is probably soon now that most other major functional development has slowed.

It's not a straightforward openGL thing to draw a "pipe" to create a 3d line. I think the best option for doing this is a geometry shader of some kind to turn raw line segments into a 3D entity.

**Comment by DRracer** [comment]
@vintagepc as a first approach, even if you do it like PrusaSlicer - draw a 8-triangle piece of tube simulating the mass of filament being extracted - would greatly help. We do not need to render millions of triangles for debugging, we need just a few.

**Comment by vintagepc** [comment]
@DRracer I'll see what I can do.... :+1: :smile:

**Comment by vintagepc** [comment]
oof.. my head hurts from the geometry calculations for this. gcode.ws doesn't have a functional example, it only uses line widths. But linewidths>1 pixel are not guaranteed in openGL, and of course we want "virtual mm" not pixels. 
So I need to offset the line in the XY plane. 

Seems trivial... but it's not. 

I tried poking through the PS gcode but there's too much noise. Perhaps someone familiar with the code could point me to the functions of interest that turn gcode line segments into square tubes.

**Comment by vintagepc** [comment]
https://github.com/linas/glextrusion might be useful

**Comment by DRracer** [comment]
@vintagepc if I had to solve this problem, I'd take the line segment as a normal vector for planes at each of its ends. In these planes I'd compute the positions of 4 points which will serve as the box/cylinder's base/top. And then just render the 8 triangles inbetween...
I know there will be cracks - i.e. the cylinders/boxes's points will not follow each other in case of turn segments etc. But for our purposes this is enough ... tbh may be even better than a smooth surface, because we would like to find the inconsistencies of extrusion if there are any.

**Comment by vintagepc** [comment]
Yes - though I'm trying to find a way to do a continuous tesselation rather than having to start/stop triangle strips for every extrusion. I'd actually gotten something working with an existing pipe extrusion sample, but it didn't handle the winding changes well; you'd get places where the default normal would flip to the other side of the polyline and the exrusion would go hourglass-shaped. 

I have no idea as to the performance penalty, hopefully this implementation won't run like crap.

**Comment by vintagepc** [comment]
Making progress... Now I just need to sort out the width calculations based on E movements...

![image](https://user-images.githubusercontent.com/53943260/94091858-585d3e80-fde7-11ea-958a-383c7a17d156.png)

**Comment by vintagepc** [comment]
Starting to look pretty good!

![image](https://user-images.githubusercontent.com/53943260/94217729-bb66d800-feb0-11ea-81c8-71e17988b68f.png)

Remaining TODOs:

- [ ] Known issue with corners and very short extrusions with high E impulses causing spikes. 
- [ ] Variable width co-linear extrusions are not shown; they're treated as a single extrusion. (just need to include E rate as part of the co-linearity calculation to detect an E volume change mid-line. 
- [ ] No automatic Z height detection. TBD, will have to make a guess based on previous layer Z. Currently hard-coded at 0.2mm
- [] No idea how this will perform with large prints in terms of performance

**Comment by DRracer** [comment]
TODO issue #2 is the most important one - ideally chop the single extrusion segment into 0.1mm slices and visualize extrusion thickness in each piece separately. With enough scale (probably including some coloring) this will enable us to see, if the firmware stepping is correct. If yes, the vertical fine artefacts must be caused by the TMC and or HW.

If caused by TMC, we could simulate its behavior and tweak the timing in FW in such a way, that the print surface gets improved.

**Comment by vintagepc** [comment]
That's one way; I'd planned to just add the E distance as a second triangle area calculation to determine if the volume:distance was changing. I don't think it'd be too hard to try both to see which is better.

Re: VFAs, I assume you're referring to the salmon-skin texture we see on the MK3 and discussed in that 50-page megathread? From what I recall the origin was concluded to be non-uniformity of the motor's step cycle; I can personally confirm they do go away if you change the motor. (but of course that doesn't mean it might not be possible to configure the driver in a way to mitigate it with the stock motors). 

I agree it would be interesting to see if the problem exists here (or, if not) whether we could simulate and reproduce it by introducing a cyclic non-uniformity in the simulated motor.

**Comment by DRracer** [comment]
@vintagepc EXACTLY ... if we even simulate a bad motor and see similar salmon-skin effect in the simulation, we can start preparing counter measures.

**Comment by vintagepc** [comment]
That would be icing on a cake indeed!

Somewhat related: Funnily enough I've started seeing one on the E-cycle again on my own printer; I suspect it's because the 3d-printed gear in my extruder is actually flexing and off-center.... One of these days I'll get around to reprinting it out of ABS or something less flexible...

**Comment by DRracer** [comment]
I'm really looking forward to this visualization, there have been so many theories around, but no-one (AFAIK) ever tried to verify, that the FW is sending the pulses correctly. If we can rule out FW, we may start tackling the TMC and the potentially bad motors.
Moreover - with LA15, the acceleration artefacts are stronger - that must be visible as well.

**Comment by vintagepc** [comment]
Yes, it's easy to latch on to a plausible explanation with relatively minimal supporting evidence. A prime example was the common adage that the MK3's Einsy was "overloaded" and could not handle higher X/Y stepping rates and result in lost steps. And we know how that turned out with https://github.com/prusa3d/Prusa-Firmware/pull/2792 completely invalidating that. (I'm rocking 0.9 degree steppers at the default 16 XY microsteps now)

**Comment by DRracer** [comment]
There is also a video showing a motor from MINI being driven by a Duet board - and while the motor is purring in the MINI, it is rotation absolutely smoothly with the Duet board ... we are doing something wrong and I'd love to find out what it is.

**Comment by vintagepc** [comment]
Fascinating!

I think we'll be able to make good use of @wavexx 's colour interpolation to colour by E-width...

**Comment by vintagepc** [comment]
well that was .... interesting. I think we may be hitting the discretization limit of the motion tracking though. And my framrate absolutely tanked after a single layer of a 25x25 square :rofl: 

![image](https://user-images.githubusercontent.com/53943260/94269031-1548bb80-ff0c-11ea-93a3-04dc2219f8d1.png)

![image](https://user-images.githubusercontent.com/53943260/94269223-5d67de00-ff0c-11ea-833e-4dfe45c77332.png)

**Comment by DRracer** [comment]
@vintagepc great progress - make longer segments (or configurable length of individual segments). For this to work we don't need a 20cm high object, a single line with acceleration and deceleration would be enough - just make sure the extrusion per millimeter is exact. I see some repeating patterns even now, but that's probably too early to judge.

**Comment by vintagepc** [comment]
So after rewriting much of the print visualizer to work in absolute motor step units rather than floats, it turns out that pattern is not discretization of the positions/float error on my part. It's the actual stepper resolution we're seeing:

```
fERate:119.000000 dXY:3.000000 dE:357
fERate:178.500000 dXY:2.000000 dE:357
fERate:119.000000 dXY:3.000000 dE:357
fERate:178.500000 dXY:2.000000 dE:357
```

In other words, sometimes X gets in 3 steps, other times 2 for the same E volume. 

_Arbitrary musings on the subject:_

That actually makes a lot of sense in the context of higher resolution steppers reducing VFAs (assuming this is the cause) since with a higher steps/mm you inherently get a better interleaving of operations.

The physics of the molten plastic helps smooth this out in reality, but if the pattern is regular enough or there are clumps of higher-volume steps then of course you're going to see it in the right lighting conditions. 

In theory one could mitigate this more with advanced planning - you could vary the travel speed (within a small window so as not to invalidate LA and molten plastic physics) such that you get even interleaving of E steps to X/Y steps....

I'm cleaning up the code a bit and getting ready to push it up as a preview. High-res E mode is enabled with a new command line argument, `--highres-extrusion`. (Off by default, it just averages the entire E volume over the total length of the segment otherwise.)

It occurs to me that this sim can also potentially be useful for investigating if the same step handling is related to the infamous 602 "inconsistent extrusion". 

Current TODOs:
- Z layer height detection for layer heights other than 0.2. I think this will be a wishlist item, MBL is going to mess with trying to get this straight from the Z value at which we're extruding and at this level we don't have access to the raw gcode to ID it from the settings. 
- Colour-based width visualization. 
- Fix positioning of the print in XY, it's off slightly.

**Comment by wavexx** [comment]
Yeah, these are implicit with bresenham. The "correctly sampled" axis is always the fastest moving during the current move.

You can simulate the effect of higher sampling rates using higher microstep counts now that they work correctly (essentially giving you the same effect as ADAPTIVE_STEP_SMOOTHING) which will reduce the difference between the effective and real pulse speed.

I didn't see the same effect you get though by actually going with a 0.9 stepper :(

**Comment by vintagepc** [comment]
> I didn't see the same effect you get though by actually going with a 0.9 stepper :(

Interesting... what motors did you go with?

**Comment by wavexx** [comment]
On Sat, Sep 26 2020, vintagepc wrote:
>> I didn't see the same effect you get though by actually going with a 0.9 stepper :(
>
> Interesting... what motors did you go with?

I still kept stock 1.8 everywhere for greater torque/speed. I was using
a 0.9 (an LDO coolstep mounted on a BMG) on the extruder for a while,
but I also reverted that a month ago to the stock BMG with a random 1.8
(so from 824 to 412 e-steps) to get greater acceleration when I noticed
that retractions were a limiting factor. E-jerk is also something I need
to retest, but I couldn't get beyond 3.5 with the old setup and that is
also to consider as it's a big limit in speed when using LA.

I was never able so far to get my hands on a low-inductance motor like
the fabled "Moons" or the newer LDO ones...

**Comment by leptun** [comment]
Why would you want a low inductance motor? Doesn’t it have lower torque (especially at speed)?
I also noticed that lower inductance motors play better with the tmc2209 drivers compared to the stock prusa ones, but it’s still not great.

**Comment by wavexx** [comment]
The idea was really to get rid of the banding ignoring everything else. It's definitely not a choice I would do today ;)

**Comment by vintagepc** [comment]
Interesting. I've got my 0.9s on X/Y. Stock firmware, no changes to limits/speeds. I have mostly run in power mode but as of the "high speed deceleration fix" I've done a few prints in stealth mode and also no longer had the layer shifting I observed there before. But it's a small sample size so not conclusive.

**Comment by wavexx** [comment]
Now that we fixed the deceleration bug we can go pretty fast, but acceleration (torque) is everything to actually save some printing time. I'll plop this here:

https://www.thregr.org/~wavexx/tmp/VID_20200920_191805_r.mp4

**Comment by vintagepc** [comment]
those poor stepper drivers :rofl: 

Colour-by-width is live! 
![image](https://user-images.githubusercontent.com/53943260/94345609-20c3e180-fff5-11ea-8074-0bc6936cd7f5.png)

**Comment by vintagepc** [comment]
I've pushed it all up to https://github.com/vintagepc/MK404/tree/114-Extrusion-visualization-take-2

I think the only thing still missing is the Z layer height detection.

**Comment by vintagepc** [comment]
Added - Extreme MBL is likely to mess with it but it appears to get a reasonable guess of the layer Z height based on the segment average Z. 

Also set the minimum segment size to 0.4mm for non-highres mode.

**Comment by DRracer** [comment]
@vintagepc very interesting results! I'm thinking about plugging-in some microstepping curve like explained in this article:
https://hackaday.com/2016/08/29/how-accurate-is-microstepping-really/

Probably we can then see similar larger scale artefacts like we observe on physical prints.

**Comment by vintagepc** [comment]
Interesting. We don't simulate/see sub-step positional changes since we operate at the native printer "step" resolution. But there should be ways to work around that either through modification of the values received or altering how things are drawn slightly to approximate such a curve.

**Comment by DRracer** [comment]
@vintagepc we now can simply recompute the real movement through that curve, I wouldn't complicate it too much. Right now you assume the motor and stepper are behaving linearly and compute the extrusion amount based on the. Just plug in some curve like that and recalculate the extrusion amount (and/or real x-y position).

**Comment by vintagepc** [comment]
I think we're saying the same thing, or at least something that has the same net effect :)

**Comment by vintagepc** [comment]
Just pushed a "flat-quad" extrusion visual mode that's not has hard on the GPU... Two triangles per segment instead of 8.

Next-up: non-uniform E-cycles....

**Comment by vintagepc** [comment]
Ummm. So. I think this takes true-to-life simulation to a whole new level. :rofl: 

Non-uniform X cycle, with a non uniformity around the half-step position:
![image](https://user-images.githubusercontent.com/53943260/94977244-e8853d00-04e5-11eb-8a6a-12f1d9c4e3c8.png)

![image](https://user-images.githubusercontent.com/53943260/94977482-dd7edc80-04e6-11eb-9fbb-efc8d57cc389.png)

That pattern looks awfully familiar...

**Comment by DRracer** [comment]
Damn, I hate being right. 
@vintagepc excellent result, keep it up. As I can see, we have 2 types of artefacts - stepper interleave and non-linear curve of the TMC/motor.
@wavexx how can we fight stepper interleave?

**Comment by DRracer** [comment]
@vintagepc "flat-quad" extrusion visual mode is completely sufficient - for our analytic purposes it looks even better than full 8-face "body" of the filament (the investigated effect is much more apparent).

**Comment by wavexx** [comment]
On Sat, Oct 03 2020, vintagepc wrote:
> Non-uniform X cycle, with a non uniformity around the half-step
> position:
> ![image](https://user-images.githubusercontent.com/53943260/94977244-e8853d00-04e5-11eb-8a6a-12f1d9c4e3c8.png)
>
> ![image](https://user-images.githubusercontent.com/53943260/94977482-dd7edc80-04e6-11eb-9fbb-efc8d57cc389.png)

I'd like to try this. Is it already in 112-*-take-2?
I guess I need to use --3d-extrusion along with --extrusion Quad_*?

**Comment by vintagepc** [comment]
The only downside to flat quad being that it's completely invisible from the bottom :rofl: 

I'm thinking that doing something about the interleave could be tricky since it's basically discretization at the resolution of the motion system. Geared extruders and smaller angle steppers (at higher microstep counts) will of course help with the problem since it gives you more choice as to when each tick needs to happen. The Einsy is certainly capable of 16 microsteps at 200 steps/mm on my 0.9s, so perhaps just a nudge to 32 microsteps on the stock motors could make that less prominent... or perhaps just the extruder.

I'm curious about what's been tried internally with X/Y linearity correction to deal with motor nonlinearity though - the feature is in the firmware and some people have found success with it for their VFAs and others have not. Was it actually added as a means to try to combat the problem previously, or is it just inherited from something else and we've never really done much with it?

Whether that means the range of adjustment isn't sufficient, or whether there's a large variability in motor characteristics (ew, I hope not!) remains to be seen. Perhaps the first thing to do there is find a way to characterize this nonlinearity under typical load. I wonder if one could somehow attach a high-resolution CNC axis scale to the bed and/or X carriage to take digital position measurements throughout the steps of the motor cycle. 

> On Sat, Oct 03 2020, vintagepc wrote: Non-uniform X cycle, with a non uniformity around the half-step position:
> I'd like to try this. Is it already in 112-*-take-2? I guess I need to use --3d-extrusion along with --extrusion Quad_*?

`--3d-extrusion` is deprecated once I added flat-quad mode, the draw style (line/quad/tube) is now controlled purely by `--extrusion`. Quad-HR is what you want, regular Quad averages things for a lower triangle count. 
My command-line was `./MK404 --extrusion Quad_HR -g lite --colour-extrusion`

The non-linearity on X is controlled by:

```
uint32_t GLPrint::GetAdjustedStep(uint32_t uiStep)
{

	return uiStep;

	auto cyclePos = uiStep%256;
	if (cyclePos<112 || cyclePos > 160) return uiStep;

	if (cyclePos>=144 || cyclePos<=128)
	{
		return uiStep-32; // lag behind 2 microstep;
	}
	else
	{
		return uiStep-64; // Lag 2 microsteps right at the midpoint.
	}
}
```

Right now it's disabled again - remove the instant return to re-enable it; and you can change this function to suit the nonlinearity you're trying to represent.  It's still present at -16 and -32, I just inflated the values for the images to distinguish it from the step interleave. 

The TMC operates at "full" resolution (256 steps) internally, when the resolution changes we adjust how many of these we increment by (so the MK3S, at 16 microsteps) will increment/decrement by 16 as its normal "step" size. 

I also pushed up my single-wall test G-code, VFA-Test.gcode. Cold extrusion and no MBL so less waiting to see the result.

**Comment by 3d-gussner** [comment]
Playing around and here an example of Marlin206_einsy printing VFA-Test.gcode
- lower part no changes in flow or LA K value
- mid section go with flow to 40
- Upper part changing flow and LA k value
- Top layers are printed with flow 100 and LA K0.00
![image](https://user-images.githubusercontent.com/25530011/95013867-5c892780-0643-11eb-8952-c281eb2177e4.png)


It looks most consistent with flow 95%

**Comment by 3d-gussner** [comment]
@vintagepc What are these lines are showing? 
![image](https://user-images.githubusercontent.com/25530011/95014081-c3f3a700-0644-11eb-928f-830c452cfad8.png)

**Comment by 3d-gussner** [comment]
It is still hard to navigate with the mouse to get a good shot. Any change we can use keys to navigate the camera, or out/input coordination?

**Comment by vintagepc** [comment]
> @vintagepc What are these lines are showing?
> ![image](https://user-images.githubusercontent.com/25530011/95014081-c3f3a700-0644-11eb-928f-830c452cfad8.png)

Those are the initial de-retractions. They show up that way because they are a high extrusion delta but with very little horizontal movement. 


> It is still hard to navigate with the mouse to get a good shot. Any chance we can use keys to navigate the camera, or out/input coordinates?
Yeah, the camera library is better than what we first had but still not great (or just misconfigured). I'll have another go at it.

**Comment by vintagepc** [comment]
@3d-gussner Just pushed up a small tweak to camera handling. seems to be better and no longer "snaps back" to the starting position every time you try to do a move. Let me know if that's better.

**Comment by 3d-gussner** [comment]
Print 100x50x50 cube with 1 perimeter with Marlin206 Einsy firmware

- first layers stock flow 95 and LA K K0.5 pla
- 2nd part flow 90
- 3rd part flow 85
- 4th part flow 80

![image](https://user-images.githubusercontent.com/25530011/95023639-7a27b280-067e-11eb-89f3-af1d5241dcaa.png)

**Comment by vintagepc** [comment]
Excellent - since this seems to be working nicely I'm going to prep some tests and merge this up to mater.

**Comment by vintagepc** [comment]
Just an observation - I've noticed that the VFAs seem to show up much more strongly during an LA lead-in and then disappear once the extruder is up to speed on X. (This is not ringing as the frequency is too high for the mass of the Y axis) Will post a pic once the print completes.

**Comment by wavexx** [comment]
Yup. Acceleration is especially bad (or let's say, less clean!) with LA. The acceleration frequency is shifted up with a fixed factor, but all additional E-steps are spread inbetween regular XYZ steps. This causes the E frequency to change continuously during acceleration _around_ the target speed, since we sum the regular stepper aliasing with E aliasing as well.

This also existed with LA1.0, but given it was a quadratic decay, the length of which it was visible was much shorter.

Sadly, to remove this issue we would need to decouple the E stepper movement from the XYZ (that is, step using a separate acceleration curve for E).  Ironically this would also reduce aliasing overall. For the AVR though this is probably an overreach :/

**Comment by vintagepc** [comment]
At that point you'd probably start getting task interleaving artifacts instead... who knows. Probably about all you could do to work around that is have some sort of external motion planner you could direct rather than controlling the steps directly.

**Comment by vintagepc** [comment]
Picture, as promised. :-)
![IMG_0002](https://user-images.githubusercontent.com/53943260/95031972-b3642080-0686-11eb-869e-7523788baf2b.JPG)

**Comment by DRracer** [comment]
@vintagepc how did you manage to make such a clean print? My stock MK3S does awful straight lines just as @3d-gussner showed in the sim. I'm shocked how exact the simulation corresponds to reality (i.e. how the printer's HW replicates the errors in driving the motors).
I do see the tiny acceleration artefacts though, that was our primary idea/motivation for visualizing extrusion.

**Comment by wavexx** [comment]
On Mon, Oct 05 2020, DRracer wrote:
> @vintagepc how did you manage to make such a clean print?

If I'm not mistaken he's using .9 steppers on XY

**Comment by vintagepc** [comment]
> On Mon, Oct 05 2020, DRracer wrote: @vintagepc how did you manage to make such a clean print?
> If I'm not mistaken he's using .9 steppers on XY

Yep, that's one of 'em. It's a somewhat modified 3S with the following being the major mods relating to print quality:

OMC 0.9 degree steppers on X/Y, 16 microsteps @ 200 steps/mm
https://www.amazon.com/gp/product/B00W98OYE4/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
They were drop in replacements, though I did add heatsinks to the TMC drivers out of caution. No customized firmware required, and sensorless homing works as expected. Last I checked the crash detection was flaky, but I haven't checked since the high-speed deceleration fix; my suspicion was that the skipped steps there could have been triggering it. 

3.5:1 geared extruder (Skelestruder) with a pancake stepper (1.8 degree) - 490 steps/mm, 16 microsteps
https://www.amazon.com/gp/product/B01LESPDCQ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

Vesconite bushings on X/Y (Doesn't help VFAs but helps with bearing noise and artifacts)

Solid mounting on a marble slab to cut down on vibration artifacts, sturdier X/Y axis printed parts for better belt tensioning. 

It occurs to me it'd be interesting to plug those steps/mm and microstep values into the simulator to see what the pattern looks like...

**Comment by vintagepc** [comment]
It's also worth noting that print is a 0.3mm layer height. Layer volume also plays a role in how visible the step discretization artifacts are.

**Comment by vintagepc** [comment]
Just tried it and the artifacts are (of course) still present but they are much finer - and I think on this scale they start to be "absorbed" into the flow characteristics of the molten plastic, which will have a natural smoothing effect:

![image](https://user-images.githubusercontent.com/53943260/95081971-5ac56f80-06e8-11eb-9f99-ed6ee99053ed.png)

That suggests that even without hardware modifiications, if we can manage to make the interleaving a little bit finer it might be possible to make them visually negligible. Maybe a combo of DEDGE and higher microstep counts could do it.

**Comment by wavexx** [comment]
I've been running with the BMG with a .9 stepper (830 e-steps), and now half of that (mostly due to the speed limit). But you can just step faster (thus reducing XY error) by increasing e-microsteps up to 64.

The BMG extrudes much smoother overall, and this becomes much more obvious at low speeds, but I can't say I noticed a decrease of VFA in prints compared to a plain MK3.

**Comment by vintagepc** [comment]
Keep in mind it depends which type of artifact you're seeing - additional microsteps doesn't help combat motor nonlinearity - only those artifacts caused by stepper interleave.

**Comment by wavexx** [comment]
Yes, but stepper interleave is what we're seeing here. My point is that the motor and/or motion of the axis as a whole is what causes most of the problem sadly.

**Comment by wavexx** [comment]
Ummh, sorry. Saw the edit too late :+1:

**Comment by wavexx** [comment]
> Picture, as promised. :-)
> ![IMG_0002](https://user-images.githubusercontent.com/53943260/95031972-b3642080-0686-11eb-869e-7523788baf2b.JPG)

Btw, .3 layers, with a .4 nozzle or bigger?

**Comment by vintagepc** [comment]
Yes, 0.4 nozzle. 0.55 extrusion width to avoid gap fill and its print time penalty on certain features in that particular part. Don't know if it matters but I also have a plated copper heat block and a plated copper nozzle.

**Comment by wavexx** [comment]
Ok, the 0.55 extrusion explains why I'm not seeing gaps between the layers. I consider .3 too high for a .4 nozzle with the default extrusion width. I'm also trying a copper block currently.

**Comment by vintagepc** [comment]
This object was a wipe block for an MMU print, but the main part was done at the default width (0.45)

![IMG_0004](https://user-images.githubusercontent.com/53943260/95089162-ce1faf00-06f1-11eb-93ba-4109254793e6.JPG)

**Comment by wavexx** [comment]
MMh, that looks quite ok. I don't have any .3 prints right here, but I generally have occasional imperfections (thin layer gaps) in long straight sections, something you definitely see immediately. It's also not unique to the MK3 (same issue with a .4 MK8 nozzle on a tevo).

**Comment by vintagepc** [comment]
I think it requires well tuned extruder tension and temperatures; I could see it easily causing issues if you're not extruding hot enough or slightly under at the flow rates/volume you get with 0.3 layer height.

**Comment by vintagepc** [comment]
Yes, I was using PLA (+-0.03mm if it matters). I normally print this stuff at 195 but had bumped it to 210 for MMU tip shaping.

**Comment by vintagepc** [comment]
Merged. Nonlinearity is disabled by default but can be enabled by swapping comments on the X Position change calls in `util/GLPrint.h`
